Extract enable_usb_storage() from mount-usb
enable_usb_storage() inserts usb-storage.ko if not already loaded, then
waits for USB storage devices to appear.

Signed-off-by: Jonathon Hall <jonathon.hall@puri.sm>

diff --git a/initrd/etc/functions b/initrd/etc/functions
--- a/initrd/etc/functions
+++ b/initrd/etc/functions
@@ -139,6 +139,24 @@ enable_usb()
 
 }
 
+# Enable USB storage (if not already enabled), and wait for storage devices to
+# be detected.  If USB storage was already enabled, no wait occurs, this would
+# have happened already when USB storage was enabled.
+enable_usb_storage()
+{
+	if ! lsmod | grep -q usb_storage; then
+		timeout=0
+		echo "Scanning for USB storage devices..."
+		insmod /lib/modules/usb-storage.ko >/dev/null 2>&1 \
+		|| die "usb_storage: module load failed"
+		while [[ $(list_usb_storage | wc -l) -eq 0 ]]; do 
+			[[ $timeout -ge 8 ]] && break
+			sleep 1
+			timeout=$(($timeout+1))
+		done
+	fi
+}
+
 list_usb_storage()
 {
 	stat -c %N /sys/block/sd* 2>/dev/null | grep usb |
